### ISSUE TITLE
Request: Thunderbird support

### ISSUE THREAD

**Issue by homlett** [kimsey0/FirefoxAutoDict#8]
Thanks to your add-on, I'm saving precious seconds every hour, meaning precious minutes every day and at least precious weeks in the end. I cannot be more thankful for that.

Now I would be beside myself with joy if a Thunderbird version would be also released.

**Comment by kimsey0** [comment]
Unfortunately, I don't use Thunderbird, so I can't help you, but you or anyone else are very welcome to take this extension as a starting point for a Thunderbird version. It's licensed under the MIT license, which allows for the free creation of derivative works.
